ports:
  - port: 9016
    visibility: public
vscode:
  extensions:
    - standard.vscode-standard
    - atishay-jain.all-autocomplete
    - xabikos.javascriptsnippets
    - octref.vetur
    - digitalbrainstem.javascript-ejs-support