[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin.28013c0e86d123a1c9bb.css"
  to = "/admin.css"
  status = 301

[[redirects]]
  from = "/admin.10d9575087eebc049c09.css"
  to = "/admin.css"
  status = 301

[[redirects]]
  from = "/admin.*"
  to = "/admin.js"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
